server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: landsreyk
    password: landsreyk
  liquibase:
    enabled: true
logging:
  level:
    socialnet:
      controller:
        NewsController: debug
auth:
  secret: socialNet
  timeLive: 86400000