server:
  port: 8086


spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: testtest55
    url: jdbc:postgresql://localhost:5432/test

auth:
  secret: socialNet
  timeLive: 216000000

socialnet:
  sheduled:
    interval: 1